### ISSUE TITLE
Remove unnecessary star 

### ISSUE THREAD

**Issue by miukimiu** [xataio/xmdb#6]
The following "star" is unnecessary. On hover, they seem clickable but they're not doing anything so they should be removed.

![image](https://github.com/xataio/xmdb/assets/2750668/4e98463c-f92a-4d78-a643-3de3b3354ac7)

**Comment by miukimiu** [comment]
Looking at this commit https://github.com/xataio/xmdb/commit/172beccab4acd48fda96e14e483916b648fa9061. @atilafassina is this a feature? It seems that it is not doing anything.

**Comment by atilafassina** [comment]
it is a feature I am currently working on. It adds rating to it. I'm going to add user feedback soon.

**Comment by miukimiu** [comment]
Ok. Closing the issue. 👍🏽
